export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/v1/auth/login",
    REGISTER: "/api/v1/auth/register",
    REFRESH_TOKENS: "/api/v1/auth/refresh",
    LOGOUT: "/api/v1/auth/logout",
  },
  JOBS: {
    PUBLIC_LIST: "/api/v1/jobs",
    PUBLIC_DETAIL: (slug: string) => `/api/v1/jobs/${slug}`,
    ADMIN_LIST: "/api/v1/jobs/admin/list",
    ADMIN_CREATE: "/api/v1/jobs/admin",
    ADMIN_DETAIL: (id: string) => `/api/v1/jobs/admin/${id}`,
    ADMIN_PUBLISH: (id: string) => `/api/v1/jobs/admin/${id}/publish`,
    ADMIN_UNPUBLISH: (id: string) => `/api/v1/jobs/admin/${id}/unpublish`,
    APPLY: (jobId: string) => `/api/v1/jobs/${jobId}/applications`,
    SAVE: (jobId: string) => `/api/v1/jobs/${jobId}/save`,
  },
  PROFILES: {
    ME: "/api/v1/profiles/me",
    BASIC_INFO: "/api/v1/profiles/me/basic-info",
    SUMMARY: "/api/v1/profiles/me/summary",
    SKILLS: "/api/v1/profiles/me/skills",
    REMOVE_SKILL: (type: string, skill: string) =>
      `/api/v1/profiles/me/skills/${type}/${skill}`,
    EXPERIENCES: "/api/v1/profiles/me/experiences",
    EXPERIENCE_DETAIL: (id: string) => `/api/v1/profiles/me/experiences/${id}`,
    EDUCATION: "/api/v1/profiles/me/education",
    EDUCATION_DETAIL: (id: string) => `/api/v1/profiles/me/education/${id}`,
    PROJECTS: "/api/v1/profiles/me/projects",
    PROJECT_DETAIL: (id: string) => `/api/v1/profiles/me/projects/${id}`,
    RESUME: "/api/v1/profiles/me/resume",
  },
  APPLICATIONS: {
    LIST: "/api/v1/applications",
    DETAIL: (id: string) => `/api/v1/applications/${id}`,
    SUBMIT: (id: string) => `/api/v1/applications/${id}/submit`,
    ANSWER: (id: string) => `/api/v1/applications/${id}/answers`,
  },
  PUBLIC: {
    CATEGORIES: "/api/v1/admin/categories",
    EXPERIENCE_LEVELS: "/api/v1/experience-levels",
    JOB_TYPES: "/api/v1/job-types",
  },
} as const;
